-- v4.3.39 — اتصال جداول عملیاتی به قرارداد
-- این Migration برای دیتابیس موجود طراحی شده است.
-- سیم‌ها / conductors عمداً مستثنا هستند چون فقط جدول مرجع انواع سیم هستند.
-- اجرای مجدد امن است: ستون، ایندکس و FK فقط در صورت نبودن ایجاد می‌شوند.

SET @db := DATABASE();

-- 1) افزودن contract_id به جداول عملیاتی
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='lines')
  AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='lines' AND column_name='contract_id'),
  'ALTER TABLE `lines` ADD COLUMN `contract_id` BIGINT UNSIGNED NULL', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='towers')
  AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='towers' AND column_name='contract_id'),
  'ALTER TABLE `towers` ADD COLUMN `contract_id` BIGINT UNSIGNED NULL', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='circuits')
  AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='circuits' AND column_name='contract_id'),
  'ALTER TABLE `circuits` ADD COLUMN `contract_id` BIGINT UNSIGNED NULL', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='personnel')
  AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='personnel' AND column_name='contract_id'),
  'ALTER TABLE `personnel` ADD COLUMN `contract_id` BIGINT UNSIGNED NULL', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='equipment')
  AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='equipment' AND column_name='contract_id'),
  'ALTER TABLE `equipment` ADD COLUMN `contract_id` BIGINT UNSIGNED NULL', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='inspections')
  AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='inspections' AND column_name='contract_id'),
  'ALTER TABLE `inspections` ADD COLUMN `contract_id` BIGINT UNSIGNED NULL', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='defects')
  AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='defects' AND column_name='contract_id'),
  'ALTER TABLE `defects` ADD COLUMN `contract_id` BIGINT UNSIGNED NULL', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='work_orders')
  AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='work_orders' AND column_name='contract_id'),
  'ALTER TABLE `work_orders` ADD COLUMN `contract_id` BIGINT UNSIGNED NULL', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='safety_incidents')
  AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='safety_incidents' AND column_name='contract_id'),
  'ALTER TABLE `safety_incidents` ADD COLUMN `contract_id` BIGINT UNSIGNED NULL', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='price_lists')
  AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='price_lists' AND column_name='contract_id'),
  'ALTER TABLE `price_lists` ADD COLUMN `contract_id` BIGINT UNSIGNED NULL', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
-- invoices از ابتدا contract_id دارد؛ فقط مطمئن می‌شویم وجود دارد.
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='invoices')
  AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='invoices' AND column_name='contract_id'),
  'ALTER TABLE `invoices` ADD COLUMN `contract_id` BIGINT UNSIGNED NULL', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- 2) ایندکس‌ها
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='lines' AND column_name='contract_id') AND NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@db AND table_name='lines' AND index_name='idx_lines_contract_id'), 'ALTER TABLE `lines` ADD INDEX `idx_lines_contract_id` (`contract_id`)', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='towers' AND column_name='contract_id') AND NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@db AND table_name='towers' AND index_name='idx_towers_contract_id'), 'ALTER TABLE `towers` ADD INDEX `idx_towers_contract_id` (`contract_id`)', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='circuits' AND column_name='contract_id') AND NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@db AND table_name='circuits' AND index_name='idx_circuits_contract_id'), 'ALTER TABLE `circuits` ADD INDEX `idx_circuits_contract_id` (`contract_id`)', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='personnel' AND column_name='contract_id') AND NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@db AND table_name='personnel' AND index_name='idx_personnel_contract_id'), 'ALTER TABLE `personnel` ADD INDEX `idx_personnel_contract_id` (`contract_id`)', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='equipment' AND column_name='contract_id') AND NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@db AND table_name='equipment' AND index_name='idx_equipment_contract_id'), 'ALTER TABLE `equipment` ADD INDEX `idx_equipment_contract_id` (`contract_id`)', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='inspections' AND column_name='contract_id') AND NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@db AND table_name='inspections' AND index_name='idx_inspections_contract_id'), 'ALTER TABLE `inspections` ADD INDEX `idx_inspections_contract_id` (`contract_id`)', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='defects' AND column_name='contract_id') AND NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@db AND table_name='defects' AND index_name='idx_defects_contract_id'), 'ALTER TABLE `defects` ADD INDEX `idx_defects_contract_id` (`contract_id`)', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='work_orders' AND column_name='contract_id') AND NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@db AND table_name='work_orders' AND index_name='idx_work_orders_contract_id'), 'ALTER TABLE `work_orders` ADD INDEX `idx_work_orders_contract_id` (`contract_id`)', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='safety_incidents' AND column_name='contract_id') AND NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@db AND table_name='safety_incidents' AND index_name='idx_safety_incidents_contract_id'), 'ALTER TABLE `safety_incidents` ADD INDEX `idx_safety_incidents_contract_id` (`contract_id`)', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='price_lists' AND column_name='contract_id') AND NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@db AND table_name='price_lists' AND index_name='idx_price_lists_contract_id'), 'ALTER TABLE `price_lists` ADD INDEX `idx_price_lists_contract_id` (`contract_id`)', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='invoices' AND column_name='contract_id') AND NOT EXISTS(SELECT 1 FROM information_schema.statistics WHERE table_schema=@db AND table_name='invoices' AND index_name='idx_invoices_contract_id'), 'ALTER TABLE `invoices` ADD INDEX `idx_invoices_contract_id` (`contract_id`)', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- 3) پاک‌سازی contract_idهای orphan قبل از ساخت FK (داده‌های قدیمی بدون قرارداد حفظ می‌شوند).
UPDATE `lines` l LEFT JOIN contracts c ON c.id=l.contract_id SET l.contract_id=NULL WHERE l.contract_id IS NOT NULL AND c.id IS NULL;
UPDATE towers t LEFT JOIN contracts c ON c.id=t.contract_id SET t.contract_id=NULL WHERE t.contract_id IS NOT NULL AND c.id IS NULL;
UPDATE circuits x LEFT JOIN contracts c ON c.id=x.contract_id SET x.contract_id=NULL WHERE x.contract_id IS NOT NULL AND c.id IS NULL;
UPDATE personnel p LEFT JOIN contracts c ON c.id=p.contract_id SET p.contract_id=NULL WHERE p.contract_id IS NOT NULL AND c.id IS NULL;
UPDATE equipment e LEFT JOIN contracts c ON c.id=e.contract_id SET e.contract_id=NULL WHERE e.contract_id IS NOT NULL AND c.id IS NULL;
UPDATE inspections i LEFT JOIN contracts c ON c.id=i.contract_id SET i.contract_id=NULL WHERE i.contract_id IS NOT NULL AND c.id IS NULL;
UPDATE defects d LEFT JOIN contracts c ON c.id=d.contract_id SET d.contract_id=NULL WHERE d.contract_id IS NOT NULL AND c.id IS NULL;
UPDATE work_orders w LEFT JOIN contracts c ON c.id=w.contract_id SET w.contract_id=NULL WHERE w.contract_id IS NOT NULL AND c.id IS NULL;
UPDATE safety_incidents s LEFT JOIN contracts c ON c.id=s.contract_id SET s.contract_id=NULL WHERE s.contract_id IS NOT NULL AND c.id IS NULL;
UPDATE price_lists p LEFT JOIN contracts c ON c.id=p.contract_id SET p.contract_id=NULL WHERE p.contract_id IS NOT NULL AND c.id IS NULL;
UPDATE invoices i LEFT JOIN contracts c ON c.id=i.contract_id SET i.contract_id=NULL WHERE i.contract_id IS NOT NULL AND c.id IS NULL;

-- 4) کلید خارجی‌ها. در صورت وجود constraint مشابه، تکرار نمی‌شود.
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='lines') AND NOT EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=@db AND table_name='lines' AND column_name='contract_id' AND referenced_table_name='contracts' AND referenced_column_name='id'), 'ALTER TABLE `lines` ADD CONSTRAINT `fk_lines_contract` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`) ON DELETE SET NULL ON UPDATE CASCADE', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='towers') AND NOT EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=@db AND table_name='towers' AND column_name='contract_id' AND referenced_table_name='contracts' AND referenced_column_name='id'), 'ALTER TABLE `towers` ADD CONSTRAINT `fk_towers_contract` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`) ON DELETE SET NULL ON UPDATE CASCADE', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='circuits') AND NOT EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=@db AND table_name='circuits' AND column_name='contract_id' AND referenced_table_name='contracts' AND referenced_column_name='id'), 'ALTER TABLE `circuits` ADD CONSTRAINT `fk_circuits_contract` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`) ON DELETE SET NULL ON UPDATE CASCADE', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='personnel') AND NOT EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=@db AND table_name='personnel' AND column_name='contract_id' AND referenced_table_name='contracts' AND referenced_column_name='id'), 'ALTER TABLE `personnel` ADD CONSTRAINT `fk_personnel_contract` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`) ON DELETE SET NULL ON UPDATE CASCADE', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='equipment') AND NOT EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=@db AND table_name='equipment' AND column_name='contract_id' AND referenced_table_name='contracts' AND referenced_column_name='id'), 'ALTER TABLE `equipment` ADD CONSTRAINT `fk_equipment_contract` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`) ON DELETE SET NULL ON UPDATE CASCADE', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='inspections') AND NOT EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=@db AND table_name='inspections' AND column_name='contract_id' AND referenced_table_name='contracts' AND referenced_column_name='id'), 'ALTER TABLE `inspections` ADD CONSTRAINT `fk_inspections_contract` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`) ON DELETE SET NULL ON UPDATE CASCADE', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='defects') AND NOT EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=@db AND table_name='defects' AND column_name='contract_id' AND referenced_table_name='contracts' AND referenced_column_name='id'), 'ALTER TABLE `defects` ADD CONSTRAINT `fk_defects_contract` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`) ON DELETE SET NULL ON UPDATE CASCADE', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='work_orders') AND NOT EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=@db AND table_name='work_orders' AND column_name='contract_id' AND referenced_table_name='contracts' AND referenced_column_name='id'), 'ALTER TABLE `work_orders` ADD CONSTRAINT `fk_work_orders_contract` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`) ON DELETE SET NULL ON UPDATE CASCADE', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='safety_incidents') AND NOT EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=@db AND table_name='safety_incidents' AND column_name='contract_id' AND referenced_table_name='contracts' AND referenced_column_name='id'), 'ALTER TABLE `safety_incidents` ADD CONSTRAINT `fk_safety_incidents_contract` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`) ON DELETE SET NULL ON UPDATE CASCADE', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='price_lists') AND NOT EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=@db AND table_name='price_lists' AND column_name='contract_id' AND referenced_table_name='contracts' AND referenced_column_name='id'), 'ALTER TABLE `price_lists` ADD CONSTRAINT `fk_price_lists_contract` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`) ON DELETE SET NULL ON UPDATE CASCADE', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='invoices') AND NOT EXISTS(SELECT 1 FROM information_schema.key_column_usage WHERE table_schema=@db AND table_name='invoices' AND column_name='contract_id' AND referenced_table_name='contracts' AND referenced_column_name='id'), 'ALTER TABLE `invoices` ADD CONSTRAINT `fk_invoices_contract` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`) ON DELETE SET NULL ON UPDATE CASCADE', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
